(import (chezscheme) (core string))
(display (string-prefix? "hello world" ""))
(display (string-prefix? "hello world" "hell"))
(display (string-prefix? "hello world" "helln"))
(display (string-prefix? "hello world" "hello world123"))
(newline)
;;;;;;;;;;;;;;;;;;;;;;;;;;
(display (string-split "" ""))
(newline)
(display (string-split " 1 2 3 4" " "))
(newline)
(display (string-split "111,211,311,411" ","))
(newline)
(display (build-string 26 (lambda (x) (integer->char (+ x (char->integer #\a))))))
(newline)
(display (string-join '("12"  "34" "56") ","))
(newline)
(display (string-find "  hello   jdkjfkd hello" "hello"))
(display (string-find "aaaaaaaaaaaa" "a"))
(newline)
(display (string-replace "  hello   jdkjfkd hello" "hello" "world"))
(newline)
(display (string-replace "aaaaaaaaaaaa" "a" "b"))
