(import (chezscheme) (rachez for) (rachez list))
(display (for/sum i <-
           (in-list (range 10000) break-when (not (<= i 100)))
           i))
(newline)
(display (for/sum i <- (in-naturals break-when (not (<= i 100)))
           i))
(newline)
(display (for/sum i <- (in-range 100 break-when (not (<= (* i i) 100)))
           i))
(newline)
(for i <- (in-range 11) (display i))
(newline)
(display (for/max i <- (in-range 11) i))
